### ISSUE TITLE
Index/Search page checklist

### ISSUE THREAD

**Issue by jayden2** [slehmann36/Group3-Real-Estate-Site#56]
Checklist for buy page
- [x] header and footer
- [x] header image
- [x] favourites image carousel
- [x] stats view
- [ ] featured properties list view
- [x] twitter view/functionality < @DoritoBandito  
- [x] sign in/up modal
